# Employee attrition using Decision Tree Algorithm
###### Below is an example of Decision Tree machine learning model. This data is taken from Kaggle data sets. This will identify employee attrition in a hypothetical oragnization. Top 6 factores that are considered resposible employee attrition are 
###### 1) Age 
###### 2) Distance From Home
###### 3) Job Satisfaction
###### 4) Percent Salary Hike
###### 5) Work Life Balance
###### 6) Years Since Last Promotion
###### Out of 34 features above six are key factors.

###### Import required Python libraries and create data frame. Also explore data 

In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HR Employee Attrition.csv')
df.head(3)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  

[3 rows x 35 columns]

In [28]:
df.shape

(1470, 35)

In [3]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [4]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [5]:
df.isnull().sum(0)

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

###### Create a data from based on key features responsible for employee attrition

In [7]:
df1 = df[['Age', 'Attrition','DistanceFromHome', 'JobSatisfaction','PercentSalaryHike',
          'WorkLifeBalance','YearsSinceLastPromotion']]
df1.head(5)

Age Attrition  DistanceFromHome  JobSatisfaction  PercentSalaryHike  \
0   41       Yes                 1                4                 11   
1   49        No                 8                2                 23   
2   37       Yes                 2                3                 15   
3   33        No                 3                3                 11   
4   27        No                 2                2                 12   

   WorkLifeBalance  YearsSinceLastPromotion  
0                1                        0  
1                3                        1  
2                3                        0  
3                3                        3  
4                3                        2

In [8]:
df1.columns

Index(['Age', 'Attrition', 'DistanceFromHome', 'JobSatisfaction',
       'PercentSalaryHike', 'WorkLifeBalance', 'YearsSinceLastPromotion'],
      dtype='object')

###### Attrition column value is categorical value. It is encoded using label encoder from sklearn

In [9]:
from sklearn.preprocessing import LabelEncoder
le_attrition = LabelEncoder()
df1['attrition_n'] = le_attrition.fit_transform(df['Attrition'])
df1.head(5)

C:\Users\GJAHAGIR\AppData\Local\Temp\ipykernel_45196\653508981.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['attrition_n'] = le_attrition.fit_transform(df['Attrition'])


Age Attrition  DistanceFromHome  JobSatisfaction  PercentSalaryHike  \
0   41       Yes                 1                4                 11   
1   49        No                 8                2                 23   
2   37       Yes                 2                3                 15   
3   33        No                 3                3                 11   
4   27        No                 2                2                 12   

   WorkLifeBalance  YearsSinceLastPromotion  attrition_n  
0                1                        0            1  
1                3                        1            0  
2                3                        0            1  
3                3                        3            0  
4                3                        2            0

In [10]:
df2 = df1.drop(columns=['Attrition'],axis='columns')

In [11]:
df2.head(5)

Age  DistanceFromHome  JobSatisfaction  PercentSalaryHike  WorkLifeBalance  \
0   41                 1                4                 11                1   
1   49                 8                2                 23                3   
2   37                 2                3                 15                3   
3   33                 3                3                 11                3   
4   27                 2                2                 12                3   

   YearsSinceLastPromotion  attrition_n  
0                        0            1  
1                        1            0  
2                        0            1  
3                        3            0  
4                        2            0

###### Create input and target values for Decision Tree model

In [12]:
inputs = df2.drop('attrition_n',axis='columns')

In [13]:
inputs.head(3)

Age  DistanceFromHome  JobSatisfaction  PercentSalaryHike  WorkLifeBalance  \
0   41                 1                4                 11                1   
1   49                 8                2                 23                3   
2   37                 2                3                 15                3   

   YearsSinceLastPromotion  
0                        0  
1                        1  
2                        0

In [14]:
target = df2['attrition_n']

In [15]:
target

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: attrition_n, Length: 1470, dtype: int32

###### Create Decision Tree model using DecisionTreeClassifier class from sklearn and train model

In [16]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [23]:
inputs = inputs.values
model.fit(inputs, target)

DecisionTreeClassifier()

###### Calculate model accuracy score

In [24]:
model.score(inputs,target)

0.998639455782313

###### Predict using model
###### Age=41
###### DistanceFromHome=1
###### JobSatisfaction=4
###### PercentSalaryHike=11
###### WorkLifeBalance=1
###### YearsSinceLastPromotion=0
###### Output of 1 indicates that attrition happned

In [25]:
model.predict([[41,1,4,11,1,0]])

array([1])

###### Predict using model
###### Age=60
###### DistanceFromHome=30
###### JobSatisfaction=2
###### PercentSalaryHike=5
###### WorkLifeBalance=0
###### YearsSinceLastPromotion=10
###### Output of 0 indicates that attrition not happened

In [26]:
model.predict([[60,30,2,5,0,10]])

array([0])

In [30]:
model.predict([[37,2,3,1,5,3]]) 

array([1])